module.exports = {
	REGISTER_SUCCESS_EMIT: 'REGISTER_SUCCESS_EMIT',
	LOGIN_SUCCESS_EMIT: 'LOGIN_SUCCESS_EMIT',
	UPDATE_PROJECT_EMIT: 'UPDATE_PROJECT_EMIT',
	
	TOKEN_STORAGE_KEY: 'TOKEN_STORAGE_KEY'
};